SRC_TOP:=../../..

include $(SRC_TOP)/rules/Makefile.inc

DEPS = \
	CarbonFootprint.h \
	tables.h \
	Bicycle.h \
	Car.h \
	House.h

OBJ = \
	main.o \
	CarbonFootprint.o \
	Bicycle.o \
	Car.o \
	House.o

include $(SRC_TOP)/rules/Makefile.rules

