SRC_TOP:=..

include $(SRC_TOP)/rules/Makefile.inc

SUBDIRS = \
	12.3-Relationships_Among_Objects \
	12.6-Case_Study_Payroll_System_Using_Polymorphism \
	12.8-Case_Study-Payroll_System_with_downcasting \
	Exercises

include $(SRC_TOP)/rules/Makefile.dir
