SRC_TOP:=../..

include $(SRC_TOP)/rules/Makefile.inc

DEPS = \
	Employee.h \
	SalariedEmployee.h \
	CommissionEmployee.h \
	BasePlusCommissionEmployee.h

OBJ = \
	main.o \
	Employee.o \
	SalariedEmployee.o \
	CommissionEmployee.o \
	BasePlusCommissionEmployee.o

include $(SRC_TOP)/rules/Makefile.rules

