SRC_TOP:=../../..

include $(SRC_TOP)/rules/Makefile.inc

DEPS = CommissionEmployee.h \
	   BasePlusCommissionEmployee.h

OBJ = main.o \
	  CommissionEmployee.o \
	  BasePlusCommissionEmployee.o

include $(SRC_TOP)/rules/Makefile.rules
