ifeq ($(MAKEFILE_DIR),)
MAKEFILE_DIR := 1

# build all subdirectories (default)
ifeq ($(SUBDIRS),)
SUBDIRS := $(shell find . -maxdepth 1 ! -path . -type d)
endif

CLEANDIRS := $(SUBDIRS:%=clean-%)
BUILDIRS := $(SUBDIRS:%=build-%)

.PHONY: subdirs $(BUILDIRS)
subdirs: $(BUILDIRS)
$(BUILDIRS): build-% : %
	$(MAKE) -C $<

.PHONY: clean $(CLEANDIRS)
clean:: $(CLEANDIRS)
$(CLEANDIRS): clean-% : %
	$(MAKE) -C $< clean

endif
