SRC_TOP:=../..

include $(SRC_TOP)/rules/Makefile.inc

SUBDIRS = \
	12.3.1-Invoking_Base_class_Functions_from_Derived_class_objects \
	12.3.2-Aiming_Derived_class_pointers_at_Base_class_objects \
	12.3.3-Derived_class_Member_function_calls_via_Base_class_Pointers \
	12.3.4-Virtual_functions_and_virtual_destructors

include $(SRC_TOP)/rules/Makefile.dir
