SRC_TOP:=../..

include $(SRC_TOP)/rules/Makefile.inc

LINKED_LIST := ../19.3-Linked_list/19.3.1-Single_linked_list/include

CFLAGS := $(CFLAGS) -I$(LINKED_LIST)
DEPS = queue.h
OBJ = main.o

include $(SRC_TOP)/rules/Makefile.rules
