SRC_TOP:=.
include $(SRC_TOP)/rules/Makefile.inc

SUBDIRS = \
	10.Operator_Overloading_Class_string \
	11.Object-Oriented_Programming-Inheritance \
	12.Object_oriented_programming-Polymorphism \
	13.Stream_IO_A_Deeper_Look \
	14.File_Processing \
	15.Standard_Library_Containers_and_Iterators \
	23.Other_topics

include $(SRC_TOP)/rules/Makefile.dir
