SRC_TOP:=.
include $(SRC_TOP)/rules/Makefile.inc

SUBDIRS = \
	10.Operator_Overloading_Class_string \
	11.Object-Oriented_Programming-Inheritance \
	12.Object_oriented_programming-Polymorphism \
	13.Stream_IO_A_Deeper_Look \
	14.File_Processing \
	15.Standard_Library_Containers_and_Iterators \
	16.Standard_Library_Algorithms \
	17.Exception_Handling_A_Deeper_Look \
	18.Introduction_to_Custom_Templates \
	19.Custom_Templatized_Data_Structure \
	23.Other_topics

include $(SRC_TOP)/rules/Makefile.dir
