SRC_TOP:=../..

include $(SRC_TOP)/rules/Makefile.inc

SUBDIRS = \
	11.3.1-Creating_and_using_a_CommissionEmployee_class \
	11.3.2-Creating_a_BasePlusCommissionEmployee_class_without_inheritance \
	11.3.3.Create_a_Inheritance_Hierarchy \
	11.3.4-Inheritance_using_protected_data \
	11.3.5-Inheritance_using_private_data

include $(SRC_TOP)/rules/Makefile.dir
